project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-2
tests:
  default:
    template: ./templates/cribl-distributed-template-arm64.yaml
    regions: 
      - us-east-2
    parameters: 
      sshKeyPair:
      instanceType:
      vpcId:
      subnetId:
      webAccessCidr:
      sshAccessCidr:
