project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-2
tests:
  default:
    template: /Users/kamiloamir/Documents/GitHub/quick-start-cribl/templates/cribl-distributed-template-arm64.yaml
    regions: 
      - us-east-2
    parameters: 
      leaderSshKeyPair: kamkeyoh
      workerSshKeyPair: kamkeyoh
      workerCount: 2
      customleaderAmiId: ami-0860d5c5f690feed3
      customworkerAmiId: ami-0860d5c5f690feed3
      vpcId: vpc-0ca13737b826351fb
      subnetIds: subnet-08718e341442f3a7d subnet-098b406b9300623ba
      instanceType: c6g.large    
      AdditionalPolicies: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      sshAccessCidr: 0.0.0.0/0
      webAccessCidr: 0.0.0.0/0
      QSS3BucketRegion: us-east-2
      DesiredCapacity: 2
      MaxSize: 2
      MinSize: 2
