project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-2
tests:
  default:
    template: /Users/kamiloamir/Documents/GitHub/quick-start-cribl/templates/cribl-single-template.yaml
    regions: 
      - us-east-2
    parameters: 
      sshKeyPair: kamkeyoh
      amiId: ami-0ef4bac28de23d41b
      vpcId: vpc-0ca13737b826351fb
      subnetId: subnet-08718e341442f3a7d
      instanceType: c5a.large    
      AdditionalPolicies: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      sshAccessCidr: 0.0.0.0/0
      webAccessCidr: 0.0.0.0/0
