project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
tests:
  default:
    template: /Users/kamiloamir/Documents/GitHub/quick-start-cribl/templates/simple-cribl-single-template-novpc.yaml
    regions: 
      - us-east-1
    parameters: 
      sshKeyPair: ami-factory-test
      amiId: ami-08c381cf6e70cdec0
      vpcId: vpc-08402416c5226a0ad
      subnetId: subnet-07200a96bfe921ff7
      sshAccessCidr: 0.0.0.0/0
      webAccessCidr: 0.0.0.0/0
      instanceType: c5a.large    
      AdditionalPolicies: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"