AWSTemplateFormatVersion: 2010-09-09
Description: Cribl LogStream Existing VPC QuickStart Deployment arm64 (qs-1s9hhq8an)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
    Order: 2
  LICENSE: Apache License, Version 2.0
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: leader Instance Configuration
        Parameters:
          - leaderSshKeyPair
          - leaderInstanceType
      - Label:
          default: Worker Instance Configuration
        Parameters:
          - workerSshKeyPair
          - workerInstanceType
          - workerCount
      - Label:
          default: Network Configuration
        Parameters:
          - vpcId
          - subnetIds
          - webAccessCidr
          - sshAccessCidr
      - Label:
          default: Advanced Settings
        Parameters:
          - customleaderAmiId
          - customworkerAmiId
          - AdditionalPolicies
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      leaderSshKeyPair:
        default: leader SSH Key Name
      leaderInstanceType:
        default: leader Node EC2 Instance Type
      workerSshKeyPair:
        default: Worker SSH Key Name
      workerInstanceType:
        default: Worker Nodes EC2 Instance Type
      workerCount:
        default: Worker Count
      vpcId:
        default: VPC ID
      subnetIds:
        default: Subnet IDs
      webAccessCidr:
        default: Web Access CIDR
      sshAccessCidr:
        default: SSH Access CIDR
      customleaderAmiId:
        default: Custom leader AMI Id
      customworkerAmiId:
        default: Custom Worker AMI Id
      AdditionalPolicies:
        default: IAM Policies for node instance profiles   
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix  
# cfn-lint: { config: { ignore_checks: [E9007] } }

Parameters:
  leaderSshKeyPair:
    Description: "REQUIRED: Name of an existing EC2 key pair for SSH access to the leader instance."
    Type: AWS::EC2::KeyPair::KeyName
  workerSshKeyPair:
    Description: "REQUIRED: Name of an existing EC2 key pair for SSH access to the Worker instance. Can be the same key as the one used for the leader instance."
    Type: AWS::EC2::KeyPair::KeyName
  workerCount:
    Description: "REQUIRED: Enter the number of worker nodes desired"
    Type: String
  customworkerAmiId:
    Description: "OPTIONAL: Advanced setting. Leave blank unless advised to assign by Cribl Support."
    Type: String
  customleaderAmiId:
    Description: "OPTIONAL: Advanced setting. Leave blank unless advised to assign by Cribl Support."
    Type: String
  vpcId:
    Description: "REQUIRED: ID of your existing VPC."
    Type: AWS::EC2::VPC::Id
  subnetIds:
    Description: "REQUIRED: List of 2 subnet Ids in different AZs. These subnets must be in the same VPC as VPC ID above."
    Type: List<AWS::EC2::Subnet::Id>
  sshAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: CIDR IP range permitted to SSH access to the instance. We recommend you set this value to a trusted IP range."
  webAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: The CIDR IP range permitted to access the LogStream web console. We recommend you set this value to a trusted IP range."
  leaderInstanceType:
    Description: EC2 instance type to provision the LogStream leader instance. If none specified, c6g.2xlarge will be used.
    Type: String
    Default: c6g.2xlarge
    AllowedValues:
      - c6g.large
      - c6g.xlarge
      - c6g.2xlarge
      - c6g.4xlarge
      - c6gd.large
      - c6gd.xlarge
      - c6gd.2xlarge
      - c6gd.4xlarge
      - m6g.large
      - m6g.xlarge
      - m6g.2xlarge
      - m6g.4xlarge
      - m6gd.large
      - m6gd.xlarge
      - m6gd.2xlarge
      - m6gd.4xlarge

    ConstraintDescription: Must contain valid instance type
  workerInstanceType:
    Description: EC2 instance type to provision the LogStream worker instance. If none specified, c6g.2xlarge will be used.
    Type: String
    Default: c6g.2xlarge
    AllowedValues:
      - c6g.large
      - c6g.xlarge
      - c6g.2xlarge
      - c6g.4xlarge
      - c6gd.large
      - c6gd.xlarge
      - c6gd.2xlarge
      - c6gd.4xlarge
      - m6g.large
      - m6g.xlarge
      - m6g.2xlarge
      - m6g.4xlarge
      - m6gd.large
      - m6gd.xlarge
      - m6gd.2xlarge
      - m6gd.4xlarge
    ConstraintDescription: Must contain valid instance type
  AdditionalPolicies:
    Default:  "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    Description: A comma separated list of Policy ARNs to add to the IAM role used by Logstream instances. Append to defaults, DO NOT REMOVE!
    Type: CommaDelimitedList 
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart-cribl-logstream
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-2'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
     uppercase letters, hyphens (-), and forward slashes (/).
    Default: logstream/
    Description: S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart-cribl-logstream'
Resources:
  ec2leaderInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - https://${S3Bucket}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}/dist_free_arm64_template.yaml
      - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-cribl-logstream-${AWS::Region}'
            - !Ref 'QSS3BucketName'
      Parameters:
        customleaderAmiId: !Ref customleaderAmiId
        leaderInstanceType: !Ref leaderInstanceType
        leaderSshKeyPair: !Ref leaderSshKeyPair
        SubnetIds: !Select [0, !Ref subnetIds]
        sshAccessCidr: !Ref sshAccessCidr
        webAccessCidr: !Ref webAccessCidr
        vpcId: !Ref vpcId
        AdditionalPolicies: !Join 
          - ','
          - !Ref AdditionalPolicies
        customworkerAmiId: !Ref customworkerAmiId
        workerInstanceType: !Ref workerInstanceType
        workerSshKeyPair: !Ref workerSshKeyPair
        DesiredCapacity: !Ref workerCount
        MaxSize: !Ref workerCount
        MinSize: !Ref workerCount
        VPCZoneIdentifier:
          - !Select [0, !Ref subnetIds]
          - !Select [1, !Ref subnetIds]
