AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Cribl LogStream QuickStart Deployment (qs-1s9hhq8an)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into a new VPC"
    Order: 1
  LICENSE: Apache License, Version 2.0 
  'AWS::CloudFormation::Interface':
    ParameterGroups:    
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - sshKeyPair
          - amiId
          - subnetIds
          - sshAccessCidr
          - webAccessCidr
          - instanceType
          - AdditionalPolicies
          - vpcId
      - Label:
          default: Cribl configuration
        Parameters: 
          - CriblVersion
          - deploymentType
          - licenseType
          - leaderNodeURL
          - workerCount    
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      vpcId:
        default: VPC for Deployment
      subnetIds:
        default: Subnets
      sshKeyPair:
        default: sshKeyPair
      amiId:
        default: amiId
      CriblVersion:
        default: CriblVersion
      deploymentType:
        default: Deployment Type
      licenseType:
        default: License Type
      leaderNodeURL:
        default: Leader Node URL
      workerCount:
        default: Number of Worker nodes
      sshAccessCidr:
        default: ssh access Cidr
      webAccessCidr:
        default: web access Cidr
      instanceType:
        default: instance type
      AdditionalPolicies:
        default: additional Policies
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Qucik Start prefix
      QSS3BucketRegion:
        default: Quick Start Region
cfn-lint: { config: { ignore_checks: [E9007] } }

Parameters:
  sshKeyPair:
    Description: "REQUIRED: Name of an existing EC2 key pair."
    Type: AWS::EC2::KeyPair::KeyName
  amiId:
    Description: "OPTIONAL: Advanced setting. Leave blank unless advised to assign by Cribl Support."
    Type: String
  CriblVersion:
    Description: "Version of Cribl LogStream you want to install"
    Type: String
    Default: 3.1.2
  vpcId:
    Description: "REQUIRED: ID of your existing VPC."
    Type: AWS::EC2::VPC::Id
  subnetIds:
    Description: "REQUIRED: List of 2 subnet Ids in different AZs. These subnets must be in the same VPC as VPC ID above."
    Type: List<AWS::EC2::Subnet::Id>
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-linux-bastion/
    Description: S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: us-east-1
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  sshAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: CIDR IP range permitted to SSH access to the instance. We recommend you set this value to a trusted IP range."
  webAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: The CIDR IP range permitted to access the LogStream web console. We recommend you set this value to a trusted IP range."
  instanceType:
    Description: EC2 instance type to provision the LogStream instance. If none specified, c5a.large will be used.
    Type: String
    Default: c5a.large
    AllowedValues:
      - c5.4xlarge
      - c5.2xlarge
      - c5.xlarge
      - c5.large
      - c5d.4xlarge
      - c5d.2xlarge
      - c5d.xlarge
      - c5d.large
      - c5a.4xlarge
      - c5a.2xlarge
      - c5a.xlarge
      - c5a.large
      - c5ad.4xlarge
      - c5ad.2xlarge
      - c5ad.xlarge
      - c5ad.large
  deploymentType:
    Description: Cribl Deployment type, Single or Distributed.
    Type: String
    Default: single
    AllowedValues:
      - single
      - distributed
  licenseType:
    Description: Cribl License type, Free, Standard or Enterprise.
    Type: String
    Default: free
    AllowedValues:
      - free
      - standard
      - enterprise
  leaderNodeURL: 
    Description: If you're working in a Cribl Cloud Environment, enter the leader node address here
    Type: String
    Default: cribl.cloud
  workerCount:
    Description: Number of Cribl Worker nodes you would like to deploy, if deploying a Single Instance, put zero (0) as the value. 
    Type: String
    Default: 0
  AdditionalPolicies:
    Type: CommaDelimitedList    
    Default:  "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    Description: A comma separated list of Policy ARNs to add to the IAM role used by Logstream instances
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Instance Configuration
        Parameters:
          - sshKeyPair
          - instanceType
      - Label:
          default: Network Configuration
        Parameters:
          - vpcId
          - subnetIds
          - webAccessCidr
          - sshAccessCidr
      - Label:
          default: Advanced Settings
        Parameters:
          - AdditionalPolicies
          - amiId
    ParameterLabels:
      sshKeyPair:
        default: SSH Key Name
      instanceType:
        default: EC2 Instance Type
      vpcId:
        default: VPC ID
      subnetIds:
        default: Subnet ID
      webAccessCidr:
        default: Web Access CIDR
      sshAccessCidr:
        default: SSH Access CIDR
Conditions:
  customAmiId: !Not [!Equals [!Ref amiId, ""]]  
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  CriblDeployment:
    Type: 'AWS::CloudFormation:Stack'
    Properties: 
        TemplateURL: !Sub 
          - https://cribl-marketplace-public-artifacts-${"AWS::Region"}.amazonaws.com/logstream/${CriblVersion}/${deploymentType}/${licenseType}_template.yaml
        Parameters:
          leaderNodeUrl: !Ref leaderNodeURL
          workerCount: !Ref workerCount
          CidrIp: !Ref sshAccessCidr
          CidrIp: !Ref webAccessCidr
          KeyName: !Ref sshKeyPair
          InstanceType: !Ref instanceType
          AdditionalPolicies: !Ref AdditionalPolicies
          subnetids:  !Ref subnetIds
          VpcId: !Ref vpcId
Outputs:
  Postdeployment:
    Description: See the deployment guide for post-deployment steps.
    Value: https://aws.amazon.com/quickstart/?quickstart-all.sort-by=item.additionalFields.sortDate&quickstart-all.sort-order=desc&awsm.page-quickstart-all=5
