AWSTemplateFormatVersion: 2010-09-09
Description: Cribl LogStream Existing VPC QuickStart Deployment arm64 (qs-1s9hhq8an)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
    Order: 2
  LICENSE: Apache License, Version 2.0
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - vpcId
          - subnetId
          - sshAccessCidr
          - webAccessCidr
          - amiId
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - sshKeyPair
          - instanceType
          - AdditionalPolicies
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      amiId:
        default: AMI ID for custom work
      sshKeyPair:
        default: SSH Key Name
      instanceType:
        default: EC2 Instance Type
      vpcId:
        default: VPC ID
      subnetId:
        default: Subnet ID
      webAccessCidr:
        default: Web Access CIDR
      sshAccessCidr:
        default: SSH Access CIDR      
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix  
  cfn-lint: { config: { ignore_checks: [E9007] } }

Parameters:
  amiId:
    Description: "Optional if sent an AMI to use by Cribl Support"
    Type: String
    Default: ''
  sshKeyPair:
    Description: "REQUIRED: Name of an existing EC2 key pair."
    Type: AWS::EC2::KeyPair::KeyName
  vpcId:
    Description: "REQUIRED: ID of your existing VPC."
    Type: AWS::EC2::VPC::Id
  subnetId:
    Description: "REQUIRED: ID of one of your existing Subnet IDs. This subnet must be in the same VPC as VPC ID above."
    Type: AWS::EC2::Subnet::Id
  sshAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: CIDR IP range permitted to SSH access to the instance. We recommend you set this value to a trusted IP range."
  webAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: The CIDR IP range permitted to access the LogStream web console. We recommend you set this value to a trusted IP range."
  instanceType:
    Description: EC2 instance type to provision the LogStream instance. If none specified, c5.2xlarge will be used.
    Type: String
    Default: c5.2xlarge
    AllowedValues:
      - c5.4xlarge
      - c5.2xlarge
      - c5.xlarge
      - c5.large
      - c5d.4xlarge
      - c5d.2xlarge
      - c5d.xlarge
      - c5d.large
      - c5a.4xlarge
      - c5a.2xlarge
      - c5a.xlarge
      - c5a.large
      - c5ad.4xlarge
      - c5ad.2xlarge
      - c5ad.xlarge
      - c5ad.large
    ConstraintDescription: Must contain valid instance type
  AdditionalPolicies:
    Default:  "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    Description: A comma separated list of Policy ARNs to add to the IAM role used by Logstream instances
    Type: CommaDelimitedList
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart-cribl-logstream
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'AWS::Region'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
     uppercase letters, hyphens (-), and forward slashes (/).
    Default: logstream/
    Description: S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart-cribl-logstream'
Resources:
  CribleDeploy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
      - https://${S3Bucket}.s3.${QSS3BucketRegion}.${AWS::URLSuffix}/${QSS3KeyPrefix}/free_arm64_template.yaml
      - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-cribl-logstream-${AWS::Region}'
            - !Ref 'QSS3BucketName'
      Parameters:
        amiId: !Ref amiId
        sshAccessCidr: !Ref sshAccessCidr
        webAccessCidr: !Ref webAccessCidr
        vpcId: !Ref vpcId
        subnetId: !Ref subnetId
        instanceType: !Ref instanceType
        sshKeyPair: !Ref sshKeyPair
        AdditionalPolicies: !Join 
          - ','
          - !Ref AdditionalPolicies