AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CriblDeployment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cribl-marketplace-public-artifacts-us-east-1.s3.amazonaws.com/logstream/3.1.3/single/template/test_deploy_template.template
      Parameters:
        sshKeyPair: ami-factory-test
        amiId: ami-08c381cf6e70cdec0
        vpcId: vpc-08402416c5226a0ad
        subnetId: subnet-07200a96bfe921ff7
        sshAccessCidr: 0.0.0.0/0
        webAccessCidr: 0.0.0.0/0
        instanceType: c5a.large  
        AdditionalPolicies: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"

