AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Cribl LogStream QuickStart Deployment (qs-1s9hhq8an)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing VPC"
    Order: 1
  LICENSE: Apache License, Version 2.0 
  'AWS::CloudFormation::Interface':
    ParameterGroups:    
      - Label:
          default: Cribl LogStream Single Deployment
        Parameters:
          - sshKeyPair
          - amiId
          - vpcId
          - subnetId
          - sshAccessCidr
          - webAccessCidr
          - instanceType
          - AdditionalPolicies
    ParameterLabels:
      sshKeyPair:
        default: sshKeyPair
      amiId:
        default: amiId
      vpcId:
        default: VPC for Deployment
      subnetId:
        default: Subnet for Deployment
      sshAccessCidr:
        default: ssh access Cidr
      webAccessCidr:
        default: web access Cidr
      instanceType:
        default: instance type
      AdditionalPolicies:
        default: additional Policies
cfn-lint: { config: { ignore_checks: [E9007] } }

Parameters:
  sshKeyPair:
    Description: "REQUIRED: Name of an existing EC2 key pair."
    Type: AWS::EC2::KeyPair::KeyName
  amiId:
    Description: "OPTIONAL: Advanced setting. Leave blank unless advised to assign by Cribl Support."
    Type: String
  vpcId:
    Description: "REQUIRED: ID of your existing VPC."
    Type: AWS::EC2::VPC::Id
  subnetId:
    Description: "REQUIRED: List of 2 subnet Ids in different AZs. These subnets must be in the same VPC as VPC ID above."
    Type: AWS::EC2::Subnet::Id
  sshAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: CIDR IP range permitted to SSH access to the instance. We recommend you set this value to a trusted IP range."
  webAccessCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: "REQUIRED: The CIDR IP range permitted to access the LogStream web console. We recommend you set this value to a trusted IP range."
  instanceType:
    Description: EC2 instance type to provision the LogStream instance. If none specified, c5.2xlarge will be used.
    Type: String
    Default: c5.2xlarge
    AllowedValues:
      - c5.4xlarge
      - c5.2xlarge
      - c5.xlarge
      - c5.large
      - c5d.4xlarge
      - c5d.2xlarge
      - c5d.xlarge
      - c5d.large
      - c5a.4xlarge
      - c5a.2xlarge
      - c5a.xlarge
      - c5a.large
      - c5ad.4xlarge
      - c5ad.2xlarge
      - c5ad.xlarge
      - c5ad.large
  AdditionalPolicies:
    Type: CommaDelimitedList    
    Default:  "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore,arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    Description: A comma separated list of Policy ARNs to add to the IAM role used by Logstream instances
Conditions:
  customAmiId: !Not [!Equals [!Ref amiId, ""]]  
Resources:
  CriblDeployment:
    Type: 'AWS::CloudFormation:Stack'
    Properties: 
        TemplateURL: !Sub 
          - https://cribl-marketplace-public-artifacts-${"AWS::Region"}.amazonaws.com/logstream/3.1.3/single/free_x86_64_template.yaml
        Parameters:
          sshKeyPair: !Ref sshKeyPair
          amiId: !Ref amiId
          vpcId: !Ref vpcId
          subnetid:  !Ref subnetId
          sshAccessCidr: !Ref sshAccessCidr
          webAccessCidr: !Ref webAccessCidr
          instanceType: !Ref instanceType
          AdditionalPolicies: !Ref AdditionalPolicies          
Outputs:
  Postdeployment:
    Description: See the deployment guide for post-deployment steps.
    Value: https://aws.amazon.com/quickstart/?quickstart-all.sort-by=item.additionalFields.sortDate&quickstart-all.sort-order=desc&awsm.page-quickstart-all=5
