project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  default:
    template: ./templates/cribl-single-template.yaml
    regions: 
      - us-west-2
